/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package various;

public class App {
 
    public String maskSensitiveData(String errorCode) {
        String regEx = "(?i)(?<=Password=).+?(?=( |$))"; 
        String regEx2 = "(?i)(?<=User=).+?(?=( |$))";
        return errorCode.replaceAll(regEx, "**redacted data**")
                        .replaceAll(regEx2, "**redacted data**");
    }

    public String getGreeting() {

        String errorMessage = "com.test.yprofile.report.exception.LookupException: Error: given update for lookup [__default]:[sssddduuudd_profile] can't replace existing spec [LookupExtractorFactoryContainer{version='v0', lookupExtractorFactory={type=cachedNamespace, firstCacheTimeout=120000, extractionNamespace={type=jdbc, table=sssddduuudd_profile, pollPeriod=PT5M, keyColumn=aliasValue, valueColumn=primaryValue, connectorConfig={createTables=true, connectURI=jdbc:mysql://ss.zz-ro-fake.us-east-1.rds.amazonaws.com:3306/lookups?useSSL=true&enabledTLSProtocols=TLSv1.2&requireSSL=true&sslmode=VERIFY_CA&trustCertificateKeyStoreUrl=file:///opt/fake/rds-fake-ca/fake.jks&trustCertificateKeyStorePassword=pass1, user=ajit, password=pass2}}}}]. with message: null' password=rere";

        String modifiedErrorMessage = maskSensitiveData(errorMessage);
        System.out.println(modifiedErrorMessage);

        return "Hello World!";

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
